### ISSUE TITLE
squeak.sh fails on Mint Sylvia when having a hidden image

### ISSUE THREAD

**Issue by codeZeilen** [squeak-smalltalk/squeak-app#13]
The situation occurs when using the Linux bundle and when there is a hidden folder in the shared/ folder which contains a .image file (for example a .git repository which contains a .image file somehwere).

The problematic line seems to be the find call in ensure_image which finds all *.image files under shared/ and seems to sort differently on Mint so that the .image file in the hidden folder appears first. 

Observed by @ekrebs5

**Comment by fniephaus** [comment]
@ekrebs5 could you please verify that https://github.com/squeak-smalltalk/squeak-app/commit/84677445f997904d3a2362dd8c541dda967c93bb fixes your issue?

**Comment by ekrebs5** [comment]
the current code leads to a warning (and no image file is opened/found)
executing the line by itself leads to the same warning (and no found file)
![grafik](https://user-images.githubusercontent.com/12158488/47738422-65ad3500-dc73-11e8-81f9-e69e430a1f42.png)

**Comment by fniephaus** [comment]
https://github.com/squeak-smalltalk/squeak-app/commit/a0884c23e4956273002ccaf715ce3fcd357cfca3 fixes the problem.
