### ISSUE TITLE
missing quotes in squeak.sh

### ISSUE THREAD

**Issue by MerlindlH** [squeak-smalltalk/squeak-app#14]
looks like there are some quotes missing [here](https://github.com/squeak-smalltalk/squeak-app/blob/squeak-trunk/templates/linux/squeak.sh#L9), which leads to problems when having spaces in the path

[this vm-version](https://github.com/OpenSmalltalk/opensmalltalk-vm/commit/e8f235ef313990acae0cda037bb0b35a9c88b7ad) seems to address a similar problem :)

**Comment by krono** [comment]
Should make sure that at least https://github.com/OpenSmalltalk/opensmalltalk-vm/commit/e8f235ef313990acae0cda037bb0b35a9c88b7ad is used for generating bundles as to not run into this problem from the vm side.

**Comment by fniephaus** [comment]
This requires a new OpenSmalltalkVM release, the VMs are loaded from http://files.squeak.org/base/

**Comment by LinqLover** [comment]
Hi, is this issue still relevant or can it be closed?

**Comment by MerlindlH** [comment]
Hey :) It looks fixed to me, probably the issue simply wasn't closed yet...
