### ISSUE TITLE
Windows builds missing on Bintray?

### ISSUE THREAD

**Issue by LinqLover** [squeak-smalltalk/squeak-app#19]
Hi,

is my assumption wrong or should [Bintray](https://bintray.com/opensmalltalk/vm/cog/202009111322#files) include builds for Win32, too? Is there something broken?

**Comment by marceltaeumel** [comment]
- https://github.com/OpenSmalltalk/opensmalltalk-vm/releases/latest-build
 - https://github.com/OpenSmalltalk/opensmalltalk-vm/releases/latest-assert-build
 - https://github.com/OpenSmalltalk/opensmalltalk-vm/releases/latest-debug-build
