### ISSUE TITLE
Builds are failing since 2021-07-06

### ISSUE THREAD

**Issue by LinqLover** [squeak-smalltalk/squeak-app#20]
Apparently, our repository does no longer exists on <travis-ci.com> (504 Gateway Timeout). As a consequence, the latest build in <http://files.squeak.org/trunk/> is from  2021-07-06.

We should either fix the Travis configuration or migrate to GitHub Actions.

**Comment by fniephaus** [comment]
+1 for moving to GHA. Travis is back online, but we don't have any credits left for daily builds.

**Comment by marceltaeumel** [comment]
See https://github.com/squeak-smalltalk/squeak-app/pull/22
