### ISSUE TITLE
`squeak.sh` cannot pass arguments with spaces to the image

### ISSUE THREAD

**Issue by LinqLover** [squeak-smalltalk/squeak-app#28]
This here is not working right now:

```
./squeak.sh -- --doit '2 + 3'
```

```
2
SyntaxErrorNotification: "Nothing more expected ->"+
3
```

I've already sketched a simple solution in my working copy that uses an array rather than string concatenation in the shell script. Will commit it soon!

**Comment by marceltaeumel** [comment]
If I recall that command-line syntax correctly, you always have to quote arguments that have spaces, right?

```
./squeak.sh -- --doit "'2 + 3'"
```

Hmm... or should those single quotes already do that? Or is that argument processed twice because of the script?

**Comment by LinqLover** [comment]
No, this doesn't work for me. Also, why should the semantics for compound/connected arguments be different for `squeak.sh` than for the `squeak` binary? :-)

**Comment by marceltaeumel** [comment]
>Also, why should the semantics for compound/connected arguments be different ...

It depends on whether there are other tools involved in the shell that already parse those arguments. It can happen. I experienced this in the CI already.

**Comment by LinqLover** [comment]
> It can happen.

But then this is a bug in any other place IMO. Whenever spacy arguments are split, a wrapper is involved that does not work fully transparent. I would consider this an anti-pattern and would try to avoid it whenever possible.

Anyway, since your proposed workaround does not even seem to work for me, would you mind giving a short review to #29? :-)

**Comment by marceltaeumel** [comment]
Sometimes you have to double, triple, quadruple escape/quote things just because. Hopefully this here is just a simpler issue.

**Comment by marceltaeumel** [comment]
> would you mind giving a short review to https://github.com/squeak-smalltalk/squeak-app/pull/29? :-)

Hehe. Do you realize that you basically just did that extra level of quoting/escaping through that array and at the end? In bash scripting you have to be careful to when you re-quote a `$1` etc. in your code.
