### ISSUE TITLE
Where is source?

### ISSUE THREAD

**Issue by xavetar** [squeak-smalltalk/squeak-app#35]
See title.

**Comment by krono** [comment]
Of what?

**Comment by xavetar** [comment]
> Of what?

I apparently did not quite understand how Smalltalk works. Code execution takes place in a [virtual machine](https://squeak.org/development/#virtual-machines)/s, if I understand correctly.

You say Open Source, but everywhere there are only [bundles](https://files.squeak.org), and the link is generally chaos. I thought Github was for storing code, not scripts for downloading bundles. Thanks, now I understand.

**Comment by krono** [comment]
THis is a repository hosting scripts for bundling [Squeak images](http://files.squeak.org/base/) with [rerspective VMs](https://github.com/OpenSmalltalk/opensmalltalk-vm/)

**Comment by krono** [comment]
This build process is outlined in 

 https://github.com/squeak-smalltalk/squeak-app/blob/squeak-trunk/README.md

The code for the VM is at https://github.com/OpenSmalltalk/opensmalltalk-vm/

The image-side development is done at http://source.squeak.org/trunk.html
(and discussed at http://lists.squeakfoundation.org/mailman3/lists/squeak-dev.lists.squeakfoundation.org/)
